#!/usr/bin/perl -w                                                                                                                                                                  

# Open the file containing the DBL alpha sequences
print "File containing sequences:";
$varseq = <STDIN>;
chomp $varseq;
open(SEQS,$varseq) || die ("Cannot open file \"$varseq\"\n");
@sequenceList = <SEQS>;
close SEQS;

# Choose a filename for the output
print "File name for output? ";
$output = <STDIN>;
open(OUT,">$output");
print OUT "analysis using: DSID_cys PoLV group_BS group classifier3 and var1_new_with sequencev2.pl\n";
print OUT "#\tName\tcys_PoLV_group\tDistinct Sequence ID\tBS_group1\tBS_group2\tVar1\tsequence\n";

#extract the names and the sequences
$sequence = join('',@sequenceList);
@name_list=($sequence =~/\>(.+)[^\>]+/g);
@seq_list =($sequence =~/\>.+([^\>]+)/g);
$nseq=$#name_list+1;

# Go through each sequence in turn finding PoLV sequences and counting cysteines
for ( $a=0; $a< $nseq; $a++){
$aplus = $a+1;
print "$aplus\n";

$seq = $seq_list[$a];
$seq =~ s/[\s\d]//g;

++$count;
#print $count,"\n";

#Find PoLV1
$PoLV1 = substr($seq,10,4);

#Define positional motifs
$b = 'WW';
$c = 'VW';

#Find PoLV2 and 3 based on the positional motifs
if ($seq =~ /$b/){
$where = rindex($seq,$b);
$PoLV2 = substr($seq,$where-4,4);
$PoLV3 = substr($seq,$where+10,4);
$message = 0;
} else {
if($seq =~ /$c/){
$where = rindex($seq,$c);
$PoLV2 = substr($seq,$where-12,4);
$PoLV3 = substr($seq,$where+2,4);
$message = 0;
} else {
$message = 1;
}}

#Find PoLV4
$PoLV4 = substr($seq,length($seq)-12,4);

#Count cysteines
$cysStart = rindex($seq,$PoLV1); $cysStart = $cysStart-10;
$cysEnd = rindex($seq,$PoLV4); $cysEnd = $cysEnd+12;
$cysCount = 0;
for(substr($seq,$cysStart,$cysEnd-$cysStart) =~ /C/ig){$cysCount++;}

#Find the length of the sequence
$seq =~ s/-//g;
$long = length($seq);

#Make the sequence ID
$distSeqID = "$PoLV1-$PoLV2-$PoLV3-$cysCount-$PoLV4-$long";

#Assign group
if ($cysCount > 4 || $cysCount == 3 || $cysCount == 1){
$cys_PoLV_group = 6;}
elsif($cysCount==4){
if($PoLV2 =~ /REY/){$cys_PoLV_group = 5;}
else {$cys_PoLV_group = 4;}}
elsif($cysCount==2){
if($PoLV1 =~ /MFK/){$cys_PoLV_group = 1;}
elsif($PoLV2 =~ /REY/){$cys_PoLV_group = 2;}
else{$cys_PoLV_group = 3;}
}
# assgn Comp1 group
if ($seq =~ /DDDVEKGLKIVFEK|DKGEKKKLEKNLKD|DSRTDKLEENLRKI|GGGGRKKLEDNLKE|GGRGRKKLEDNLIE|GGRGRKKLEDNLKE|GGRGRKQLEENLQK|GKKKEKEKIYGNIE|GPKQEKKELEENLK|GPSQEKIKLEENLK|GPSQEKKKLEENLK|HEQGNNKLEAILKT|HEQGNNKLEARLKT|HEQGYNKLEAILKT|HEQGYNKLEAISKT|HNHIKKPLLENLEQ|HNHKKKPLLDNLEK|HNHKKKPLLENLEQ|HNNKKKALLDNLEK|HNQKKINLEKSLHR|HQQRKGKLEENLRN|HQQRKRKLEENLRN|HSKEKEKLQTNLKN|KNESEIKRKEKLQR|KNESEKNTKKKLQG|KNESEKRTKEKLQG|NDADKVEKGLQVVF|NDADKVQKGLQVVF|NDDVEKGLKIVFEK|NDEDDVEKGLKIVF|NDKDAAQKVLRTVF|NDKDAVQKGLRAVF|NDKDAVRHGLKVVF|NDKDYVENGLKKVF|NDKEKDQRKKLDEI|NDKEKDQRKKLDEN|NDKVEKGLQVVFGK|NDKVEKGLREVFKK|NDKVEKGLREVFRK|NDKVENGLKKVFDK|NDKVENGLREVFKK|NDNVEKGLKAVFRK|NDNVEKGLKKVFDK|NDNVENGLREVFKK|NDQDDVEKGLKIVF|NDQDEVWNGLRSVF|NEDDKVQKGLQVVF|NEDVEKGLKVVFKK|NEDVEKGLKVVFQK|NEEDAVQKGLKKVF|NEEDAVQKGLKVVF|NEEDAVQKGLRAVF|NEKDAVQNGLKKVF|NEKVEIGLKKVFDK|NEKVEIGLKKVFEK|NEKVEIGLKKVFKK|NEKVEYGLRKLFKK|NEMVEIGLKKVFKK|NENVEKGLKIVFEK|NENVEKGLKKVFDK|NENVEKGLQVVFGK|NEQDEVWKGLRDVF|NGDYKEKVSNNLKT|NGDYKEKVSNNLRA|NGDYKKKVSNNLKT|NKDDKIEKSLRAIF|NKDDKVEKGLRAIF|NKDDKVQKGLKAVF|NKDDKVQKGLQVVF|NKDDKVQKGLRAVF|NKHDNIEKGLREVF|NKNVEIGLKKVFDK|NKNVEIGLKNVFKN|NKQEKEKREKLDEN|NKQRKKILQEKLEN|NNDDDKIKKGKLRG|NNDNDKIKKEKLQE|NNDNDKIKKEKLRG|NNDNDKIKKGKLRG|NNDNDKVKKEKLQN|NNDNDKVKKEKLRG|NNDNDRVKKEKLQN|NNDVEKGLDVVFKK|NNDVEKGLKVVFKK|NNDVVKGLDVVFKK|NNEKDMREKQKLQS|NNEKDMTEKQKLQS|NNESEIKRKEKLRG|NNESEKKKREELQG|NNETDKEQKVKLEK|NNHDNVEKGLKAVF|NNHDNVEKGLKKVF|NNHDNVENGLKAVF|NNHDNVENGLREVF|NNKEKEKIEKSLQN|NNKENEKLQENLKR|NNVDAVQEGLKVVF|NPEDKVHEGLKVVF|NPEVEKGLKAVFRK|NPEVENGLREVFNK|NPQDKVQEGLKNVF|NPQDKVQEGLKVVF|NPQDKVQKGLREVF|NQEDKVQEGLKVVF|NRKEKGKLQTNLKN|NSDDKVEKGLREVF|NSDDKVENGLKKVF|NTVDKIHEGLKVVF|NTVDKVHEGLKVVF|NVHDKVEKGLQVVF|NVHDKVEKGLQVVL|NVHDKVEKGLREVF|NVHDKVERGLREVF|NVHDKVETGLREVF|SEKVEYGLRKLFKK|SNKEKEKIENSLQN|TDKDAVQKGLRAVF|TDKDDVENGLREVF|TDKDEVKEGLKVVF|TDKDEVWKGLRAVF|TDKDYVENGLKAVF|TDKDYVENGLKKVF|TDKVENGLKEVFDK|TDKVENGLKKVFDK|TDKVENGLKKVFDN|TDNDAVQKGLRAVF|TDNDEVWKGLGSVF|TDNDEVWKGLRSVF|TDNDEVWTGLRSVF|TDNVEKGLRAVFGK|TDNVENGLREVFKK|TEKDDVEKGLKIVF|VNGNDKLESNLKKI|YDEKEKNRRKQLEN|YNERDRAQKKKLQD|YNERDRDKKRKLQE|YNERDREKKRKLQD/){
$BS_group1 = 1;}
elsif($seq =~ /AKNDYTGDHPNYYK|ALKHYKDDTKNYYQ|ARYKKDEEDGNYYK|ARYKKDEEDGNYYQ|DKNRGKLGALSLDD|DNNSDKLRDLSVDK|EHYEDVDGSGNYLK|EHYKDVDGSGNYYK|EKNYPDDGSGNYSK|EKNYYNDGTGNYYK|EYYEDKDPDKNYYQ|EYYNDTNNKINYVK|GIIDYDHDGPHYYK|GINAYNDGSENYYK|GINDCDRDGPEYYK|GINDYDGDGPEYYK|GINDYDRDGPEHYK|GINDYDRDGPEYYK|GINDYNDGSGNYFK|GINDYNDISGNYYK|GKKYYNDETGNYYK|GKKYYNDGSGNYYK|GKKYYNDGTGNYVK|GKNYPDDGSGNFYK|GKNYPDDGSGNYYK|GKQYYNDENGNYYK|GQTYPDDGSGNYYK|HHYKDDDISGNYSK|IEARYKKDDDNYYQ|IETRYENDGPNYYQ|IETRYGSDTTNYYQ|IHNYDDNGSGNYYK|IKNDKTLNNLSNGQ|ISYYNADEKGNFYK|KAKERYKDIKNYYQ|KAKYEDLKTLPIDD|KARYKDRKDPNYYK|KDHYKDEKDGNFFQ|KDHYQDDGTGNYYK|KDYYNADEKGNYYK|KEEYGDLKDVPIDD|KEISDYDNDPNYYK|KEKYGDLKDVPIDD|KEYYQDDGTGNYYK|KGINDYDGDPNYYK|KHYADEDGSGNYYK|KHYAHDDGSGNYYK|KHYAHDDGSVNYYK|KHYAHGDGSGNYLK|KHYAHGDGSGNYSK|KHYAHGDGSGNYYK|KHYTDTHGSIDYDK|KIKDYDGDGPEYYK|KINDYDGDGPEYYK|KITHYDDISGNYYK|KKHYENDTDKNYYQ|KKHYKKDEDPNYYK|KKKKKGLSELSTEK|KKVYPEDVTGNYFK|KKVYPEDVTGNYYK|KNAYPDDGFGNYYK|KNAYPDDGSGNYFK|KNAYPDDGSGNYYK|KNDYNPDGSGNYFK|KNDYNPDGSGNYYK|KNENTDLNKLTTEK|KNKNTKLSTLTLEK|KNNDRTLNNLSIGQ|KNYNYDEDGPEYYK|KNYNYDKDGPEYYK|KNYYNPDEAGNYYK|KNYYNPDGAGNYYK|KNYYNPDGSGNYYK|KPHYKDDGFGNYYK|KQHYKDDGSVNYYK|KQHYKEDKDENYYK|KQNNKKLKDLTDKH|KRYYNDDTDDNFYQ|KRYYNDDTDNNFYQ|KRYYNDDTDNNLYQ|KSYYDADEKGNYYK|KSYYNADEKGNYYK|KSYYNADGEGNFYK|KTIYADLKDVEIDD|KTSNSNLKELSLDK|KTSNSNMDTLSLEQ|KTSNTNMNTLSLDK|KVHYKENKDGNYVK|KVHYKENKDGNYYK|KVKYPDLKDLQIDD|KVKYPDLNDIEIDD|KVKYPDLNDVEIDD|KVKYQDLKDVEIDD|KYYNDTNNKINYVK|LKKHYQKDAPNYYK|LKTRYKKDDDNYYQ|LQARYKKDGDDFFK|LQERYNDPKGDFFQ|LQTRYTNDGDNYFK|MESNANLKKHTLER|NEHYKEVKNGNYVK|NHYKDDDGSGNYYK|NHYKDDDISGNYSK|NHYKDDDISGNYYK|NHYKDDNGSENYYK|NHYKDDNGSGNYYK|NKNKPPLDKLSVDK|NKNKSPLDKLSLEQ|NKNNVPLDKLSLDK|NKNNVPLHNLSLDK|NVHYKDDGSENYYK|NVHYKDDGSGNYYK|NVHYKEVKNGNYVK|NYNYDEDGSGNYVK|NYNYDEDGSGNYYK|NYYADGDKSGNYYK|NYYNNTGNNANYAK|NYYNNTGNNVDYVK|NYYNNTGNNVNYAK|PHYTNDRGLADYVK|QGIIDYDNDPNYYK|QISDYDGDGPEYYK|QISDYTGDHPNYYK|QKHYEDDGSGNYYK|QKIYEDINNLPIDD|QKIYKDLNNLPIDD|QKNNSALKKLTDKQ|QKSDSSLQRLSIEK|QNYYADDGSGNYSK|QNYYADDGSGNYVK|QNYYKDDPKKNYYK|QQNNNTLENLTDKQ|REHYKEVKNGNYIK|REHYKEVKNGNYYK|REKYKDLKDLPIDD|REKYKDLKDVEIDD|RERYKDLKDVEIDD|RHYADHDKSGNYYK|RIRHYDDGSGNYSK|RIRHYDDGSGNYYK|RITHYNDGSGNYVK|RITHYNGVSGNCVK|RKNNSSLRKLTNEQ|RNENNNLGKLSNEQ|RVKETYKDDPNYYK|SDYKDDDGSGNYYK|SDYKDDDIDGNYYK|SDYKDDDIDGNYYQ|SHYADHDKSGNYLK|SHYADHDKSGNYYK|SHYEDGDKSGNYYK|SHYEDKDKSGNYIK|SHYTDTHGSIDYDK|SKINDYDGDPNYYK|SKITDYDNDPNYYK|SVQERYGNDPNFFQ|TETLYKDEEGNYLK|THYADEDGSENYYK|THYADEDGSGNYVK|TVKETYKDDPNYYK|TVKGTYKDDPYYYK|VKAHYKKDAPYYYK|VKAHYQKDAPNYYK/){
$BS_group1 = 1;}
elsif($seq =~ /CAARGNDLYSKNIG|CAARYHPGYFKKSD|CDAPKDANYFIGSG|CDAPQKVDYFRKGS|CDAPQKVDYFRKIS|CDAPRDADYFKNVA|CDAPRDADYFRKGS|CDAPRDAHYFLKSS|CDAPRDANFFIKNS|CDAPYKSRYFIQSE|CDAPYKSRYFMQSE|CDASYKSGYFMQSE|CDTEESDTYFKQSS|CEAPENAYIIKRRI|CEAPGDAHYFRKGP|CEAPKDANYFIGSG|CEAPQKVDYFRKGL|CEAPQKVDYFRKGS|CEASKNANFFIKDS|CEASKNANFFIKNS|CFADGSEEYFIKSS|CFADGSEEYFIQSE|CFADGSEEYFIQSS|CFAHNTEEYFIKSE|CGAGAKDTYFTYSK|CGAGARDEYFIKPS|CGAGEKDTYFTYSK|CGAGEKDTYFTYSN|CGAGEKDTYFVQLD|CGALPKSAYFLQSE|CGALPKSAYFMQLE|CGALPKSAYVLQSE|CGATMNDIFSKNIG|CGTGENDTYFKNSS|CIAPRDAHYFLKSS|CKAKEGDIYSKTTD|CKAPEDADYFRKGS|CKAPGDVNFFIKNS|CKAPGDVNYFRKIS|CKAPKDADYFRKGS|CKAPKDAHYFLKSS|CKAPKDANFFIKIS|CKAPKDANYFIGSG|CKAPKGANYFRKES|CKAPNGANYFRKKS|CKAPPKVDYSRNIS|CKAPQDANYFRKGL|CKAPQDANYFRKIS|CKAPQDANYFRNIS|CKAPQDANYFRNVS|CKAPQDANYFTKES|CKAPQGANYFRNIS|CKAPQKANYFRKGS|CKAPQKVDYFRKGS|CKAPQSVHYFIKTS|CKAPTGADYFKKKS|CKAPTGADYFVYKP|CKAPTGAHYFLKSS|CKASKNANFFIKNS|CKASRNAHYFLKSS|CKASRNANYFRKAL|CKASRNANYFRKIS|CNAPDKAEYFVYKS|CNAPDNVNYFRKYS|CNAPGDAHYFRKDP|CNAPGDVHYFRKDP|CNAPNISGYFMQSE|CNAPNISGYFMQSG|CNAPYDANYFRKTS|CNAPYDANYVRRKS|CNAPYDANYYRKYS|CNAPYDANYYRQTC|CNAPYEAQYFIKPS|CNAPYEAQYFIKSS|CNAPYEAQYYIKSS|CNAPYKAQYYIKSS|CNAPYKAWYFMHSE|CNAPYKSRYFIQSE|CNAPYKSRYFMHSE|CNAPYKSRYFMQSE|CRAPKNAHYFIKSS|CRAPNEANYFKNVA|CRAPNGANYFRKGL|CRAPQKANYFKNVA|CSADDSEDYFIQSE|CSADDSEDYFIRSE|CSADGSEDYFIKSS|CSADGSEEYFIQSE|CSADGSEEYFKKQS|CSAGPKDTYFIKSG|CSAGQKDTYFIKPN|CSAPDNAKYFKPPK|CSAPDNAKYVKYFP|CSAPDYAKYFRQTC|CSAPGDAKYVKNFP|CSAPGDAKYVKYFP|CSAPGDVNYFRKES|CSAPGDVNYFRKFS|CSAPGDVNYFRKGL|CSAPGDVNYFRKIS|CSAPHNAQYVKYVP|CSAPRDADYFIKNS|CSAPRDAQYFIKSS|CSAPYCADYFKKKS|CSAPYDANYVRRKS|CSAPYEAQYFIKSS|CSAPYEAYYFTYKS|CSAPYGANYYRKYS|CSAPYHPGYFRQSK|CSAPYKSQYFIKSS|CSAPYNAHYFIKSS|CSAPYYADYFKKKP|CSAPYYADYFKKKS|CSAPYYADYFKSVA|CSAPYYADYFRKGS|CSAQNNEVYFINSE|CSVPYEAYYFTYKS|CTAPDKANYFIYKS|CTAPDNVNYFRKYS|CTAPYGANYYRKYS|CVAGEGNTYFIQLD|CVAPENAYFRKTEA|CYAPNNANYFIGSG|CYIPYCVNYFKNIS|CYIPYYVNYFKDIS|CYIPYYVNYFKKKS|CYIPYYVNYFKKTP|CYIPYYVNYFKKTS|CYIPYYVNYFKNIS|YKAPKDAHYFLKSS|YKAPQDANYFRNVS|YKAPRKADYFRNIS|YKAPRKANYFIYKS/){
$BS_group1 = 1;}
elsif($seq =~ /AVSSNKCGHNDMNV|EFTGGYCGRDETDV|EFTSGYCGRNETNV|FENAGKCGHNDNRV|FENAGKCRRNDNKV|FLYPKCGHNNKNDL|FSDNGHCGRNETNV|FSDNGPCGRKELIV|FSNEHCGHHNNDDP|FSNEHCGHYKNGDP|FSNEYCGHKKNEDP|FSNEYCGHYKNGDP|FSNNGPCGRNETDV|FSNNKCGHSNGGDP|FSNPKCGHSNGGDP|FSNRGPCGRNETDV|FSNSGKCGGKEAPV|FSNSGPCGRKELTV|FSNSGTRGRKELTV|FSNSKCGHHNNDGP|FSSDRCGHNNNDGP|FSSEGKCGHKEGTV|FSSEYCGHYKNGDP|FSSHGKCGHNEGAP|FSSQGQCGHTEGTV|FSSSGPCGRDEAPV|FTDDGKCGHYEGAP|FTDGHCGRTQEGHV|FTDIGKCGGKEAPV|FTDIGKCGHGDKDV|FTDIGKCGHKQGNV|FTDIGKCGHNEGAP|FTDIGKCGHNKGSV|FTGGGQCGRNETDV|FTGGGQCRRNDNSV|FTNDGKCGHTEGTV|FTNDGKCGHYEDAP|FTNDGKCGHYEDNV|FTNDGKCGHYEGAP|FTNDGKCGHYENNI|FTNDGKCGRYEGAP|FTRQGYCGHSETNV|FTSAGKCRHNDNSV|FTSAGKCRRNDNSV|FTSEGKCGHNDNRV|FTSEGKCGRNETNV|FTSEGQCGHDENKV|FTSEGQCGHNDKSV|FTSEGQCGHSETNV|FTSEGQCRRNDNSV|FTSEGQRGHSETNV|FTSEGRCGHSETNV|FTSHGKCGHSEGAP|FTSHGKCGRNETNV|FTSIGKCGHNKGSV|FTSQGQCGHKEGTV|FTSQGQCGHSETNV|FTSQGQCGHTEGTV|FTSQGQCGRNERNV|FTSQGYCGHSETNV|FTSQGYCGRKEAPV|FTSQGYCGRKELTV|FTSVGYCGHNKGIR|FTSVGYCGHNKGSV|FTTEGYCGRDEGAP|FTTEGYCGRNEGAP|FWDRKCGHSNEGAL|FWDRKCGHSNEGAP|FWDRKCGHSNGGDP|IFSNEHCGHKQGSV|IVSFDQCGHNDMDV|IVSFDQCGHNDVDV|KFSERKCGHDENAP|KFSERKCGHNEGSP|KFSSDRCGHNEGDP|LFDYNCGHHKDNNV|LFSDGHCGNKDGTV|LFSDHKCGHEESRV|LFSDYKCGHYEDAP|LFSDYKCGHYEGSP|LFSNAYCGHYEGSP|LFSNDYCGHKQGNV|LFSNPKCGHEQGNV|LFSNPKCGHEQGTV|LFSNPKCGHKQGKV|LFSNRQCGHDENKV|LFSNRQCGHEQGNV|LFSNRQCGHGEHEV|LFSNRQCGHNEGAP|LFSNSKCGHDENKV|LFSNSKCGHDESKV|LFSNSKCGHEQGNV|LFSNSKCGHRQGNV|LFSNYKCGHYEDAP|LFWDRKCGHDERNV|LLFSNYKCGHYEGS|LWNDKCGHHVDKDV|NFSNPKCGHDEGIV|NFSNPKCGHKQGNV|NLILTHPKCGHDTD|PSYIKCGHNNKDDP|PSYLKCGHNNKDDP|SEGKCGHKETERDL|SFADAYCGRGDENV|SFSDHKCGHDENAP|SFSDHKCGHGDKDV|SFSDHKCGHYEGAP|SFSDRKCGHYEGAP|SFSNDYCGHNENKV|SFSNDYCGHRQGSV|SFSNEYCGHRQGSV|SFSNGQCGHRDENV|SFSNPKCGHEQGNV|SFSNPKCGHGDNEV|SFSNPKCGHGEHEV|SFSNPKCGHNENKV|SFSNSKCGHGEHEV|SFSSEYCGHEQGNV|SFSSEYCGHGDNEV|SFSSEYCGHRQGSA|SFSSEYCGHRQGSV|SFTNGQCGHNEENV|SFTNPKCGHDENKV|SFTNPKCGHGDNEV|SFTNPKCGHGEHEV|SFTNPKCGRGDNEV|SLILPYSKCGRDTD|SQGQCGRNENNGYP|SSTNTQCRCATNDV|TEGYCGRNENNGYP|TFSGYWCGHYEGAP|TFSNDYCGHGEHEV|TFTYTKCGHDENKV|TSEGQCGHNDKMRP|TVSFDQCGHNDMDV|TVSFDQCGHNDMHV|TVSNAKRREGDENP|TVSSNKCGHNDMDV|VFSNRQCGHYEDAP|VFSNRQCGHYEDVP/){
$BS_group1 = 1;}
else {$BS_group1 = 0;}

# assgn Comp2 group
if ($seq =~ /DKGEKKKLEENLKN|DQERKHLLEKRLET|DQERKQHLEKRLET|DQQEKAKLENNLKR|DQQEKLYLENNLKK|DRKEKVKLEENLKN|GPDQEKKKLEENLR|GPNQEKKLLENKLK|HEPGIQHLEKRLES|HEPGIQYLEKRLES|HEPGKQHLEERLEQ|HEPGKQHLEERLER|HEPGKQHLGERLEQ|HEQGINRLEARLKT|HEQGNNRLEARLKT|HEQGYNRLEARLKT|HNRRKEKLETRLEE|HQQRKHLLEKRLET|KKKLEENLRNIFKN|NDEEKKKRDELEKN|NTHESAQRKKLEEN|REKGKSRLEARLKT|REPGKQHLEERLER|YNEKDQEEKRKLQE|YNETDKVQKAILQQ|YSQKYKDEKSKLEE/){
$BS_group2 = 1;}
elsif($seq =~ /AKNHYNDTSKNYYK|ARDHYNDTSGNYYQ|DAKKHYGDDENYYK|IEHYKDDPEENFYE|IKSNYNDSEGNYFK|IKSQYDDNEGNYFK|KDHYKGDEANNYFQ|KDNNTKLNDLSIQE|KKTNPALKSFTNEE|KNNNNELNNLSLDK|KNNNNKLSNLSTKE|KSSYNDDGTGNYFK|KSYYKNDNDRNYFK|NKNKSPLDKLSLDK|NKNNPPLYKLSLEK|NNNAAKLSELSTAQ|NYYEDNDTDKNYYQ|QKENGDINTLKPEE|QNKNENLKSLSLDK|QNNNTKLQNIPLHE|QRNNIKLQNIPLHE|QRNNIKLQTLTLHQ|SAKEHYQDTENYYK|TRYKKDDEDGNFFQ|VKDRYQNDGPDFFK/){
$BS_group2 = 1;}
elsif($seq =~ /CDAGAADEYFKKSG|CDAGQKDTYFKQSS|CEAGTSDKYFRKTA|CEAKSDDKYNVIGP|CGAGMKDIYSKTMN|CGAPKEAKYFRKTA|CGAPSDAQYFRNTC|CGASEDAKYKVIGP|CGATMNDIFSKNIR|CGATVDDIFSKNIR|CGATVDDISSKNIR|CGTEDKDTYFIKSG|CGVEENAKYFRESS|CHAPPDAQYTKKGP|CKAEVDDIYSKTAN|CKAKEGDIYSKTAN|CKAKEGDIYSKTMN|CKAKKGDIYSKTMN|CKAKKGGIYSKTMN|CKANDDAEYFRKKD|CKAPDKANYFEPPK|CKAPDKANYFKPPK|CKAPEEDHYFKPAQ|CNAPKDANYFEYNS|CNAPTGADYFVYKP|CNAWGNTYFRKTCS|CRAEEKDIYSKTTD|CRAEEKDTYFKNRE|CRAEEKEIYSKTTD|CRAEEKGTYFKNRE/){
$BS_group2 = 1;}
elsif($seq =~ /EFSGGKCGHKDNNV|EFTDGHCGHNEENV|EFTDGHCGHRQGNV|EFTGGQCGRDGENV|ESNKGQCRCFSGDP|ESNMGQCRCFSGDP|ESNMVQCRCFSGDP|ETHGYCRCVNRVDV|FSNDQCGHNNGGAP|FSNDQCGHNNRGDP|FWYPKCGHHVKQDV|FWYPKCGHHVKQEV|FWYPKCGHHVRQDV|FWYPKCSHHVKQDV|GANAIKAGDNVSIV|GGHYKNCHCIGGDV|GGTYKNCRCASGNV|ILFDYKCAHDNDKV|KFSNPKCGHNEGSP|LFYYKCGHYVYKDV|LWNDKCGHHVKQDV|LWNYKCGHHVNQDV|LWNYNCGHHVNQDV|LWNYNCGHHVNRDV|PCSVQKCTCINGDP|PNKCRCEDANADQV|SFTNGQCGRDGENV|SWYPKCGHHVKQDV|TLFDYKCGHDENAP|TLWNEKCGHGDYNL|TPTQGKCHCIDGTN|TPTQGKCHCIDGTV/){
$BS_group2 = 1;}
else {$BS_group2 = 0;}

 # assgn Comp3 group
if ($seq =~ /KKKKKQNGKETERE|AKDRYNDNDKNFFK|CDADGSYFRATCSD|CDARDNAEYFRKTP|CDDKLASASYFRPT|CEAEGAYFHATCSD|CEAGGSQYFRRTCS|CEANGTYFRATCDI|CGVKDNRYFRPTCG|CHAKVGDTYFRPTC|CHAVHNAEYFRDAC|CKADENDRYSANIE|CKAEGASYFHATCD|CKAEGASYFHATCS|CKAEGAYFHATCSD|CKANGTYFRPTCSD|CKAPQDANYFRQAV|CKAPQDANYFRQTV|CNAWGNTYFRATCG|CRCDKDKGANADQV|CRCDKEKGGKADQV|CRCKDENGKNTDQV|CRCKDKNGRPDDQV|CSDEDKKLKDASYF|CSEDLKNSSYFHAT|FCRCGDDKKPNDQV|GGRGRKKLDDKLEE|GGRGRKKLDDKLKE|GKNAGKGSDDVSIV|GNNKRRQQLEKNLK|GTKERYKDTDNYYE|GTQVRCRCPKGDQV|GVSHGRCGHRDENV|HKQKKNQLEERLKT|HYKDEDDNEGNYFQ|IEARYNDDDPDFFK|IKGSGGKAGDVNIR|IKGSGGKAGDVNIV|KENNEELNSLENEQ|KENNSKLKSLTDDQ|KGNNRKLSTLEDEE|KKDRYKDDTTNYFQ|KKKKKQNETERDQL|KKKRGQTETERDQI|KKRYEGDEAKNFLK|KNENTKRSTLTLEK|KTRYQGDEANNFYK|LKARYNGDGDNYYK|LKTRYGSDALDFYQ|LQERYNDPKENFYR|LQKRYGGDGGNFFK|LRDRYHKDGPDYYQ|NDEEKKKRDELDDK|NDEEKRQRQKIEDN|NDKEKDQRKKLQQN|NKKENKQREQLEKN|NKKKEKLEENFKKY|NKKKERLDENLKTI|NKKKSENKREKEKL|NNEEKKQRKQLDDK|NNKEKEKLEKNLRQ|NNKRRQQLESKLKE|NPQESARRDKLESK|QARYEGDKENYFFQ|QARYKDDAKKNFYR|QARYQDENGGNFFK|QCRCPKTSGNVNIV|QERYQDDDKKIFYR|QKHYQDDNGGNYFQ|QKHYQDKNGGNFFK|QKQCRCGDGDVTIV|QKRYEGDKNNNFFK|RCEGVKGAKDGDQV|RCKKEDGKDDTDQV|RCPKSRDDKPNTDP|RCPKSRDKKPNDQV|RCPKSRDNNPDDQV|RCPKTSGAKADDQV|SETNNKCRCTIETV|SIKSQYDEDKNFFK|SPTKDFCRCKDDEV|TDKSKAGNGDVSIV|TLQERYKGDPDFFK|TSTQGKCQCINFSV|TSTQGKCRCINFSV|VVSSGKCGNRDQDV|YNEKDQKEKKQLQD|YNEKDRNEKKQLQD/){
$BS_group3 = 1;}
else {$BS_group3 = 0;}

  # assgn Comp4 group
if ($seq =~ /AEKRYGSDTKNFYQ|AIECYNDGSGKFYQ|AIERYNDGSGNFYQ|AIGRYNDGSGNFYQ|AKTRYNGDGDNYYK|AQTHYNDNDGNYFQ|ARERYKDGDGNYYQ|CDAGSGNNYFRHTC|CDAPNGGVHYFRKT|CDARDNAKYFRATC|CGAPEEAHYFRKTC|CGAPEEAHYFRNAC|CGAPEEAHYFRNTC|CGAPKEAHYFRKTC|CHVVSGNDYFRRTC|CHVVSGNNYFRRTC|CKAEQNDKYFRDAC|CKAPGNAQYFRNTC|CNADNDAFYFRPTC|CNAGGGKYFRNTCD|CNVQDDAKYLEESN|CSDDLKDASYFRQT|CSDDNKLANASYFR|CSVEDAYYFRPTCG|DKGEETELEKNLKK|DKGEETKLENNLKE|DNRKDREQREQLEK|DQQEKVKLQNNLKS|EYYEEDKKEGNFYQ|EYYKEDKKEGNFYQ|KKLRYNGDRQNYYK|KNSRYENDSPNYYK|KPTGEKCQCIDGAV|LKTRYNGDDPDFFK|LKTRYNGDKENFYQ|MDKNEDLKDLTLDQ|NKKKDKLEENLKNM|NKKKNEKDREKERL|NKQEKDRLQNKLKE|NKQEKEKRGELESK|NKTQNNCRCAAGDV|NNQEKEKLQENLRQ|NREEREKEKLQNNL|NRKEKEKEKLQENL|NRKEKEKVKLQKNL|NRKEKEKVKLQNNL|NRKEREKEKLQNNL|NRKEREKVKLQQRL|NSHQSKCRSNNAEV|PSHCRCDDKPNTDP|QDRYKDEPDNDFLK|QGNYPTLKDLSPDQ|QSHYKNDDDPNFYQ|RCKDKKGEHDTDQV|RPTGGKCQCIDQTV|SETNNNCQCIDFSV|SHVKDKCTCVSGDP|TKHNTKLGQLTLDQ|TLKTRYGSDENYYK|TNEKCRCDGANVDP|TPTEGNCRCIDTNV|TPTNHNGRCIGATV|TPTNHSCRCIGATV|TPTRGNCQCIGQAV|TWTNEKCQCATHDV|TWTNEKCQCVTHDV|TWTNEKCRCVTHDV|YNEIDREQKKQLQE/){
$BS_group4 = 1;}
else {$BS_group4 = 0;}

 # assgn Comp5 group
if ($seq =~ /DRKEKVKLEKKLKE|NKQEKKQRKQLDDN|NNKEKNRRDELEKN|DNREKTKLEKNFKK|DNKKDKTDKLQEQL|KRKKKNQKETETER|YDDEEKKQRDELES|KKKKKKTETERDQL|KKKKKQNGKETETE|NKKKNPTERDKLEE|NKKKEKLEQNLQKI|NKQEKEKRDELESK|NPQESAQRKQLEEK|DKGEKKKLEEHLKT|NDEEKKKRDELDKK|NDEEKTKRDELESK|NKQEKRQRKQLDDN/){
$BS_group5 = 1;}
elsif($seq =~ /AKDHYQKDGDKFFQ|AQTYYNDDKENYFQ|GNNNSTLTGLPLHK|GVKDHYQDTTDYFQ|IKSNYNDSEGNYYL|KDHYQDDNGGNYFQ|KDRYKGDKKNNYYQ|LKTRYQNDTGDFFK|LQERYNGDKENYYK|NYYKDDTDKKNFYQ|QARYEGDKNNNFFQ|QARYNDDNGGNYYK|QENNSILSTLKDDQ|QKRYEGDKENYFFQ|QNYYKGDADNNYYK/){
$BS_group5 = 1;}
elsif($seq =~ /CDAHGTYFRPTCGD|CDAHGTYFRPTCSD|CDDDDKLANASYFR|CDDDNKLGGYSYFR|CDDRLGGNAYFRNT|CDDRLSNSKYFHAT|CDKKLSNASYFRPT|CDVKSGNNYFRHTC|CDVVSGKYFRHTCN|CGTHEGDTYFRPTC|CKADDSNRYFRATC|CKADTGNAYFRPTC|CKAEGASYLHATCS|CKAEGAYFRPTCSD|CNAGGYSYFRATCG/){
$BS_group5 = 1;}
elsif($seq =~ /AGKPKAGNGDVNIV|CRCKDKKGKNTDQV|CRCKDKKTGSNADP|CRCVKEKGAKADQV|DDKPKAGNGDVTIV|DGKPKAGNGDVTIV|KNNCRCSDKANIDP|NGDKPDDDKPNTDP|NKCRCKGDNPNTDP|QARKKCRCEGANIV|RCKDENLTKETDQV|RCKKNDGTSETDQV|RCPKISGGKANDQV|RCRSKNFTKETDQV|SQAHDKCTCNNGDV|TATNHNCRCNGDQV|YQANNKCTCNNGDV/){
$BS_group5 = 1;}
else {$BS_group5 = 0;}

 # assgn Comp6 group
if ($seq =~ /AKEHYNYDTENYFQ|ALQDRYTDNKNYYQ|AQKRYKDTDKNYYK|AQKRYKNNDENYFQ|AQTYYNDNGGNYYK|CDDDNNLSKAKYFR|CDEDKKLAGASYFR|CDEENKLGGYLYFR|CDHRLGGYSYFRPT|CEAGSGKYFRGTCG|CGAGGSQYFRATCN|CKADASSAYFHATC|CKAEGAYFHATCSE|CKAKEADKYFRNTC|CRCKKKDNTPDDQV|CSEDLNNSSYFHAT|CSEQLKDNRYFRQT|CSEQLSNSKYFRLT|DDKSKAGKGDVNIV|DGDKPGQDRPNTDP|EKHYKGDTDKNYYK|GDDEPGNEKPNIDP|GDDKPDDDKANVDP|GTNAGKAGGNVTIV|GTQVRCRCPNGDQV|GVKARYGSDKDFFQ|IKSKYNGDTTDFFK|KAGKAGGDGDVTIV|KAKDRYKGDPYYYK|KARYEGDDKKNFYQ|KENNEKLKSLTDDQ|KKKRGQTEREKLEN|KPKDGKANDNVSIV|KRKAIKAGDNVSIV|KRNNSKLSTLKDDQ|LQKRYNDDTGDFFQ|NDDQPGHDKPNTDP|NGDKPGQDKANTDP|NGDQPGNDKENIDP|NKKENKQRKKLEEN|NKKKIKTETERDKL|NKKKKQKGKETERE|NKQEKKKRDELDKN|NNDQPNADKANTDP|NNGKGEKLEAKIKE|NPQEKDQRKKLQQN|NPQEKEKREDLEKN|NRKKKQTERDQLES|PGKPKAGNGDVTIV|QARNQCRCDGANIV|RCKKEDGKNDTDQV|SKKEKEKRKQLDDK|YDDEEKKKREDLEK|YDQKEKEQRDDIEK|YNQKDREQKKKLQD|YNQKDRKEKAKLQE|YNQKDRKEKQKIQD/){
$BS_group6 = 1;}
else {$BS_group6 = 0;}

 # assgn Comp7 group
if ($seq =~ /ANKTTGNTGDVNIV|CDAGGGTYFRFTCS|CDDDNKLSNASYFR|CDDDNKLSNASYVR|CDDKLSNASYFRPT|CEAPKDSKYFRQTC|CGAPNDAQYFRLTC|CHVVSGNNYFRHTC|CNAGSYQYSQPTCS|DKEKAGKAGDVNIV|DKGEETKLEKNLKE|EYYKKDDKDPNFYK|GGRGKGKEKLEQKL|GTKERYNDTDNYFQ|IRSKYDETSENYFQ|KKNFYRLREDWWTA|KKPGTNADNPNIDP|KPKAGNGDGDVNIV|KTRYKDDDKKNFYR|LKTRYEHDAADYYQ|LKTRYQHDAADYYQ|LKTRYQHDAPDYYQ|LQKRYNGDGDNYFQ|NDEEKNRRDKLEKS|NDKEKDQRKVLDKK|NKKEKKKRDELENN|NKKKDKLEDNLQKI|NKREKRRLEDNLQK|NKTQNNCRCAINDV|NNKEKEQRKKLEKN|NNKKDKLQIKLKEY|NNQEYEHRKSLEKN|NPEEIKQRKKLDDK|NSKEKNRRENLENN|NTKEKEKRKQLDDK|PLSQQKCSCPNAGV|QARYKGDDNNNYSK|QGKYPKLNGLPLDE|SRYKKDDKDPHFYQ|SSAHNNCTCVDGDP|SWTQGDCRCKTNDV|TATQGNCRCIGATV|TLAHKNCTCISGDP|TLAHNNCTCVDGDP|TRTNNDCQCINFSV|YKKDEDDKDPNYYQ/){
$BS_group7 = 1;}
else {$BS_group7 = 0;}


# assgn Var1 group
if ($seq =~ /NVHDKVEKGLREVF|NVHDKVETGLREVF|APNKEKIKLEENLKK/){
$Var1 = 1;}
else {$Var1 = 0;}

print OUT $count,"\t";

#Check for problems with the sequence
$first = substr($seq,0,2);
$end = substr($seq,length($seq)-2,2);



if ($first eq 'DI' && $end eq 'LR' && $message == 0){ 
print OUT "$name_list[$a]\t";
print OUT "$cys_PoLV_group\t";
print OUT "$distSeqID\t";
print OUT "$BS_group1\t";
print OUT "$BS_group2\t";
print OUT "$Var1\t";
print OUT "$seq\n";
} 
elsif ($message == 1){
print OUT "$name_list[$a]\t";
print OUT "?\t";
print OUT "?\t";
print OUT "$BS_group1\t";
print OUT "$BS_group2\t";
print OUT "$Var1\t";
print OUT "$seq\n";
}
else{
print OUT "$name_list[$a]\t";
print OUT "$cys_PoLV_group\t";
print OUT "$distSeqID **Check**\t";
print OUT "$BS_group1\t";
print OUT "$BS_group2\t";
print OUT "$Var1\t";
print OUT "$seq\n";
}
}

close OUT;



